CREATE TABLE TBL_FILE (
     ID NUMBER PRIMARY KEY,
     FILE_PATH VARCHAR2(255) NOT NULL,
     FILE_SIZE NUMBER DEFAULT 0,
     POST_ID NUMBER NOT NULL,
     CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
     UPDATED_DATE DATE NOT NULL,
     CONSTRAINT FK_FILE_POST FOREIGN KEY(POST_ID)
     REFERENCES TBL_POST(ID)
);
