CREATE TABLE TBL_TEAM_POST(
    ID NUMBER PRIMARY KEY,
    TEAM_ID NUMBER,
    END_DATE DATE NOT NULL,
    INFORMATION VARCHAR2(255),
    POST_READ_COUNT NUMBER DEFAULT 0,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TEAM_POST_TEAM FOREIGN KEY(TEAM_ID)
    REFERENCES TBL_TEAM(ID)
);

CREATE SEQUENCE SEQ_TEAM_POST;

SELECT * FROM TBL_TEAM_POST;

SELECT * FROM
( SELECT ROWNUM R, P1.*
  FROM (SELECT ID, TEAM_ID, END_DATE, INFORMATION, POST_READ_COUNT, CREATED_DATE, UPDATED_DATE
        FROM TBL_TEAM_POST
        ORDER BY POST_READ_COUNT DESC ) P1
        WHERE ROWNUM <= 10) P2
WHERE P2.R >= 6;