CREATE TABLE TBL_TEAM_MEMBER(
    ID NUMBER PRIMARY KEY,
    MEMBER_ID NUMBER,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MEMBER_USER FOREIGN KEY(MEMBER_ID)
    REFERENCES TBL_MEMBER(ID)
);

CREATE SEQUENCE SEQ_MEMBER;

SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_MEMBER(
                       ID, U_ID
) VALUES (1,2);