CREATE TABLE TBL_MATCHING(
                             POST_ID NUMBER PRIMARY KEY,
                             MATCHING_STATUS VARCHAR2(255) NOT NULL,
                             TEAM_ID NUMBER,
                             SPORT_KIND_VALUE VARCHAR2(255) NOT NULL,
                             CHOICE_AM_PM VARCHAR2(255) NOT NULL,
                             TIME_REGIST VARCHAR2(255) NOT NULL ,
                             DATE_REGIST VARCHAR2(255) NOT NULL ,
                             TIME_CORDINATE VARCHAR2(255) NOT NULL,
                             DATE_CORDINATE VARCHAR2(255) NOT NULL,
                             CITY VARCHAR2(255) NOT NULL ,
                             LOCAL_CITY VARCHAR2(255) NOT NULL ,
                             LOCAL_CITY_DETAIL VARCHAR2(255) NOT NULL,
                             CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
                             UPDATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
                             CONSTRAINT FK_MATCHING_POST FOREIGN KEY(POST_ID)
                                 REFERENCES TBL_POST(ID),
                             CONSTRAINT FK_MATCHING_TEAM FOREIGN KEY(TEAM_ID)
                                 REFERENCES TBL_TEAM(ID)

);

CREATE SEQUENCE SEQ_MATCHING;

SELECT * FROM TBL_MATCHING;

ALTER TABLE TBL_MATCHING
    MODIFY CHOICE_AM_PM VARCHAR2(255);

ALTER TABLE TBL_MATCHING
    ADD CONSTRAINT FK_MATCHING_SPORT_KIND FOREIGN KEY (SPORT_KIND_ID)
        REFERENCES TBL_SPORTS_KIND_RADIO(ID);

ALTER TABLE TBL_MATCHING
    ADD CHOICE_AM_PM VARCHAR2(255);


ALTER TABLE TBL_MATCHING
    DROP CONSTRAINT FK_MATCHING_SPORT_KIND;

ALTER TABLE TBL_MATCHING
    DROP COLUMN CHOICE_AM_PM;
