CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER(
    ID NUMBER PRIMARY KEY,
    MEMBER_NAME VARCHAR2(255) NOT NULL,
    MEMBER_EMAIL VARCHAR2(255) NOT NULL,
    MEMBER_NICKNAME VARCHAR2(255) NOT NULL,
    MEMBER_PHONE VARCHAR2(255) NOT NULL,
    MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
    MEMBER_GENDER VARCHAR2(255) NOT NULL,
    MEMBER_POINT NUMBER NOT NULL,
    MEMBER_INTRODUCE VARCHAR2(255),
    MEMBER_SPORT_KIND VARCHAR2(255),
    MEMBER_POSITION_KIND VARCHAR2(255),
    MEMBER_SPORT_HISTORY VARCHAR2(255),
    MEMBER_BIRTH DATE NOT NULL,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATE DEFAULT CURRENT_TIMESTAMP
);

SELECT *FROM TBL_MEMBER;

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_EMAIL, MEMBER_NICKNAME, MEMBER_PHONE, MEMBER_PASSWORD,
                       MEMBER_GENDER, MEMBER_POINT, MEMBER_INTRODUCE, MEMBER_SPORT_KIND, MEMBER_SPORT_HISTORY,
                       MEMBER_BIRTH, CREATED_DATE, UPDATED_DATE)
VALUES (1,'TESTER', 'test@gmail.comt', 'tester123',
        '123-456-789','test1234', '남성',1000,
        null,null,null,
        TO_DATE('2002-04-09','YYYY_MM_DD'), CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
