CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER(
    ID NUMBER PRIMARY KEY,
    MEMBER_NAME VARCHAR2(255),
    MEMBER_EMAIL VARCHAR2(255),
    MEMBER_NICKNAME VARCHAR2(255),
    MEMBER_PHONE VARCHAR2(255),
    MEMBER_PASSWORD VARCHAR2(255),
    MEMBER_GENDER VARCHAR2(255),
    MEMBER_POINT NUMBER DEFAULT 0,
    MEMBER_INTRODUCE VARCHAR2(255),
    MEMBER_SPORT_KIND VARCHAR2(255),
    MEMBER_POSITION_KIND VARCHAR2(255),
    MEMBER_SPORT_HISTORY VARCHAR2(255),
    MEMBER_KAKAO_EMAIL VARCHAR2(255),
    MEMBER_KAKAO_PROFILE_URL VARCHAR2(255),
    MEMBER_STATUS NUMBER DEFAULT 1,
    MEMBER_LOGIN_TYPE VARCHAR2(255) DEFAULT 'NORMAL',
    MEMBER_BIRTH DATE,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TBL_MEMBER
    MODIFY MEMBER_EMAIL VARCHAR2(255);

ALTER TABLE TBL_MEMBER
    ADD MEMBER_LOGIN_TYPE VARCHAR2(255) DEFAULT 'NORMAL';

ALTER TABLE TBL_MEMBER MODIFY MEMBER_BIRTH NULL;

SELECT *FROM TBL_MEMBER;
