CREATE TABLE TBL_FILE (
    ID NUMBER PRIMARY KEY,
    FILE_PATH VARCHAR2(255) NOT NULL,
    FILE_SIZE NUMBER DEFAULT 0,
    POST_ID NUMBER NOT NULL,
    TEAM_ID NUMBER NOT NULL,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ATTACHMENT_POST FOREIGN KEY(POST_ID)
    REFERENCES TBL_POST(ID),
    CONSTRAINT FK_ATTACHMENT_TEAM FOREIGN KEY (TEAM_ID)
    REFERENCES TBL_TEAM(ID)
);

CREATE SEQUENCE SEQ_ATTACHMENT;
