CREATE TABLE TBL_POST(

                         ID NUMBER PRIMARY KEY,
                         POST_TITLE VARCHAR2(255) NOT NULL,
                         POST_CONTENT VARCHAR2(255) NOT NULL,
                         CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
                         UPDATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
                         TYPE NUMBER NOT NULL
);
CREATE SEQUENCE SEQ_POST;

SELECT * FROM TBL_POST;
<<<<<<< HEAD



=======

--     ID NUMBER PRIMARY KEY,
--     POST_TITLE VARCHAR2(255) NOT NULL,
--     POST_CONTENT VARCHAR2(255) NOT NULL,
--     CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
--     UPDATED_DATE DATE NOT NULL,
--     TYPE NUMBER NOT NULL
-- );

CREATE SEQUENCE SEQ_POST;
>>>>>>> master

